databaseChangeLog:
  - changeSet:
      id: create_category_table
      author: max_olivero
      changes:
        - createTable:
            tableName: category
            columns:
              - column:
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                  name: id
                  type: BIGINT
              - column:
                  name: parent_id
                  type: BIGINT
              - column:
                  name: country_id
                  type: BIGINT
              - column:
                  name: name
                  type: VARCHAR
              - column:
                  name: enabled
                  type: BIT
              - column:
                  name: is_leaf
                  type: BIT

  ## Product_Price Table
  - changeSet:
      id: create_product_price_table
      author: max_olivero
      changes:
        - createTable:
            tableName: product_price
            columns:
              - column:
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                  name: id
                  type: BIGINT
              - column:
                  name: category_id
                  type: BIGINT
              - column:
                  name: price
                  type: DOUBLE
              - column:
                  name: highlighted_price
                  type: DOUBLE
              - column:
                  name: is_in_offert
                  type: BIT
              - column:
                  name: name_offert
                  type: VARCHAR
              - column:
                  name: have_discount_percentage
                  type: DOUBLE
              - column:
                  name: created_on
                  type: TIMESTAMP
              - column:
                  name: updated_on
                  type: TIMESTAMP
              - column:
                  name: enabled
                  type: BIT

  - changeSet:
      id: create_products_table
      author: max_olivero
      changes:
        - createTable:
            tableName: products
            columns:
              - column:
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                  name: id
                  type: BIGINT
              - column:
                  name: name
                  type: VARCHAR
              - column:
                  name: brand_id
                  type: BIGINT
              - column:
                  name: price_id
                  type: BIGINT
              - column:
                  name: country_id
                  type: BIGINT
              - column:
                  name: provider_id
                  type: BIGINT
              - column:
                  name: category_id
                  type: BIGINT
              - column:
                  name: created_on
                  type: TIMESTAMP
              - column:
                  name: updated_on
                  type: TIMESTAMP
              - column:
                  name: deleted_on
                  type: TIMESTAMP
              - column:
                  name: enabled
                  type: BIT

  ## ProductImages Table
  - changeSet:
      id: create_product_images_table
      author: max_olivero
      changes:
        - createTable:
            tableName: product_images
            columns:
              - column:
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                  name: id
                  type: BIGINT
              - column:
                  name: product_id
                  type: BIGINT
              - column:
                  name: image_id
                  type: BIGINT

